In [1]:
import os
import sys
import importlib
import autoreload

%load_ext autoreload
%autoreload 2

In [2]:
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
from src.lstm import lstm_classifier

In [4]:
lstm_model = lstm_classifier(num_wds=200, 
                        embed_size=300,
                        lstm_size=128, 
                        dense_size=[1024, 256], 
                        class_num=2, 
                        learning_rate=0.001,
                        batch_size=64, 
                        root_dir=module_path)



Cleaned data exists, load directly from pickle file

No meta graph found. Start to build graph from scratch


The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use keras.layers.BatchNormalization 

In [15]:
# [n.name for n in lstm_model.graph.as_graph_def().node]

In [5]:
X_sample, y_sample = lstm_model.data_helper.get_next_batch(epoch=0)

In [6]:
X_sample.shape

(128, 200)

In [7]:
y_sample.shape

(128, 2)

In [75]:
lstm_model.train_model(steps=1, epochs=5000, validate_every=100)

Training loss: 0.680621, accuracy: 0.59375
Better accuracy found. LSTM model saved
----------------- Step 0: validation accuracy 0.504 ----------------
Training loss: 0.674884, accuracy: 0.59375
Training loss: 0.826987, accuracy: 0.40625
Training loss: 0.765152, accuracy: 0.4375
Training loss: 0.70991, accuracy: 0.609375
Training loss: 0.73863, accuracy: 0.59375
Training loss: 0.706198, accuracy: 0.53125
Training loss: 0.74606, accuracy: 0.40625
Training loss: 0.699543, accuracy: 0.4375
Training loss: 0.686817, accuracy: 0.625
Training loss: 0.698351, accuracy: 0.484375
Training loss: 0.694036, accuracy: 0.578125
Training loss: 0.699801, accuracy: 0.4375
Training loss: 0.699125, accuracy: 0.546875
Training loss: 0.68806, accuracy: 0.515625
Training loss: 0.686105, accuracy: 0.59375
Training loss: 0.730933, accuracy: 0.453125
Training loss: 0.690041, accuracy: 0.5
Training loss: 0.714755, accuracy: 0.5
Training loss: 0.756479, accuracy: 0.390625
Training loss: 0.703539, accuracy: 0.4687

Training loss: 0.699575, accuracy: 0.46875
Training loss: 0.669323, accuracy: 0.59375
Training loss: 0.705636, accuracy: 0.546875
Training loss: 0.700849, accuracy: 0.46875
Training loss: 0.705637, accuracy: 0.46875
Training loss: 0.696244, accuracy: 0.5625
Training loss: 0.691843, accuracy: 0.578125
Training loss: 0.698076, accuracy: 0.484375
Training loss: 0.680653, accuracy: 0.609375
Training loss: 0.698325, accuracy: 0.46875
Training loss: 0.71104, accuracy: 0.4375
Training loss: 0.713246, accuracy: 0.484375
Training loss: 0.695921, accuracy: 0.5
Training loss: 0.722961, accuracy: 0.375
Training loss: 0.696779, accuracy: 0.515625
----------------- Step 200: validation accuracy 0.50528 ----------------
Training loss: 0.699394, accuracy: 0.53125
Training loss: 0.713658, accuracy: 0.4375
Training loss: 0.69837, accuracy: 0.484375
Training loss: 0.700448, accuracy: 0.484375
Training loss: 0.691885, accuracy: 0.53125
Training loss: 0.696582, accuracy: 0.53125
Training loss: 0.695938, ac

Training loss: 0.582783, accuracy: 0.703125
Training loss: 0.530977, accuracy: 0.78125
Training loss: 0.517983, accuracy: 0.734375
Training loss: 0.495196, accuracy: 0.75
Training loss: 0.58221, accuracy: 0.671875
Training loss: 0.525913, accuracy: 0.765625
Training loss: 0.661318, accuracy: 0.59375
Training loss: 0.610573, accuracy: 0.65625
Training loss: 0.575557, accuracy: 0.703125
Training loss: 0.611838, accuracy: 0.6875
Training loss: 0.587651, accuracy: 0.671875
Training loss: 0.635901, accuracy: 0.625
Training loss: 0.657052, accuracy: 0.578125
Training loss: 0.52687, accuracy: 0.734375
Training loss: 0.621859, accuracy: 0.703125
Training loss: 0.501115, accuracy: 0.71875
Training loss: 0.60539, accuracy: 0.640625
Training loss: 0.607741, accuracy: 0.671875
Training loss: 0.67975, accuracy: 0.625
Training loss: 0.598433, accuracy: 0.703125
Training loss: 0.630754, accuracy: 0.6875
Training loss: 0.647663, accuracy: 0.640625
Training loss: 0.539117, accuracy: 0.8125
Training los

Training loss: 0.42219, accuracy: 0.828125
Training loss: 0.406066, accuracy: 0.796875
Training loss: 0.36697, accuracy: 0.859375
Training loss: 0.544508, accuracy: 0.78125
Training loss: 0.472953, accuracy: 0.8125
Training loss: 0.211684, accuracy: 0.953125
Training loss: 0.368324, accuracy: 0.828125
Training loss: 0.330749, accuracy: 0.875
Training loss: 0.282374, accuracy: 0.90625
Training loss: 0.513495, accuracy: 0.765625
Training loss: 0.462114, accuracy: 0.828125
Training loss: 0.315551, accuracy: 0.890625
Training loss: 0.404075, accuracy: 0.84375
Training loss: 0.48911, accuracy: 0.765625
Training loss: 0.502505, accuracy: 0.796875
Training loss: 0.374929, accuracy: 0.828125
Training loss: 0.358091, accuracy: 0.859375
Training loss: 0.283219, accuracy: 0.921875
Training loss: 0.379041, accuracy: 0.890625
Training loss: 0.371063, accuracy: 0.84375
Training loss: 0.372571, accuracy: 0.828125
Training loss: 0.339703, accuracy: 0.875
Training loss: 0.568425, accuracy: 0.734375
Tra

Training loss: 0.261173, accuracy: 0.890625
Training loss: 0.333395, accuracy: 0.890625
Training loss: 0.336609, accuracy: 0.890625
Training loss: 0.317698, accuracy: 0.859375
Training loss: 0.340766, accuracy: 0.890625
Training loss: 0.282659, accuracy: 0.875
Training loss: 0.275991, accuracy: 0.890625
Training loss: 0.193476, accuracy: 0.9375
Training loss: 0.399733, accuracy: 0.828125
Training loss: 0.328709, accuracy: 0.890625
Training loss: 0.374391, accuracy: 0.84375
Training loss: 0.265118, accuracy: 0.90625
Training loss: 0.245358, accuracy: 0.9375
Training loss: 0.3329, accuracy: 0.875
Training loss: 0.388867, accuracy: 0.84375
Training loss: 0.378735, accuracy: 0.828125
Training loss: 0.426134, accuracy: 0.859375
Training loss: 0.195414, accuracy: 0.9375
Training loss: 0.352516, accuracy: 0.890625
Training loss: 0.16574, accuracy: 0.953125
Training loss: 0.205717, accuracy: 0.953125
Training loss: 0.270386, accuracy: 0.890625
Training loss: 0.210267, accuracy: 0.921875
Traini

Training loss: 0.150514, accuracy: 0.953125
Training loss: 0.201078, accuracy: 0.953125
Training loss: 0.405781, accuracy: 0.875
Training loss: 0.202732, accuracy: 0.90625
Training loss: 0.276117, accuracy: 0.90625
Training loss: 0.291773, accuracy: 0.875
Training loss: 0.191158, accuracy: 0.921875
Training loss: 0.316553, accuracy: 0.890625
Training loss: 0.222148, accuracy: 0.921875
Training loss: 0.378765, accuracy: 0.875
Training loss: 0.199402, accuracy: 0.921875
Training loss: 0.215883, accuracy: 0.9375
Training loss: 0.198521, accuracy: 0.921875
Training loss: 0.317008, accuracy: 0.890625
Training loss: 0.21672, accuracy: 0.9375
Training loss: 0.378218, accuracy: 0.859375
Training loss: 0.285682, accuracy: 0.90625
Training loss: 0.132858, accuracy: 0.984375
Training loss: 0.286478, accuracy: 0.90625
Training loss: 0.164545, accuracy: 0.9375
Training loss: 0.312223, accuracy: 0.875
Training loss: 0.328904, accuracy: 0.921875
Training loss: 0.217954, accuracy: 0.90625
Training los

Training loss: 0.234856, accuracy: 0.921875
Training loss: 0.158198, accuracy: 0.953125
Training loss: 0.107602, accuracy: 0.96875
Training loss: 0.246698, accuracy: 0.9375
Training loss: 0.27203, accuracy: 0.921875
Training loss: 0.0760961, accuracy: 0.96875
Training loss: 0.140376, accuracy: 0.9375
Training loss: 0.0972924, accuracy: 0.96875
Training loss: 0.258874, accuracy: 0.921875
Training loss: 0.196657, accuracy: 0.9375
Training loss: 0.1877, accuracy: 0.9375
Training loss: 0.376996, accuracy: 0.875
Training loss: 0.155171, accuracy: 0.953125
Training loss: 0.125424, accuracy: 0.953125
Training loss: 0.136587, accuracy: 0.96875
Training loss: 0.135973, accuracy: 0.9375
Training loss: 0.130842, accuracy: 0.953125
Training loss: 0.239935, accuracy: 0.921875
Training loss: 0.306048, accuracy: 0.890625
Training loss: 0.279612, accuracy: 0.90625
Training loss: 0.125133, accuracy: 0.96875
Training loss: 0.21689, accuracy: 0.921875
Training loss: 0.147414, accuracy: 0.9375
Training lo

Training loss: 0.111858, accuracy: 0.953125
Training loss: 0.183573, accuracy: 0.953125
Training loss: 0.205127, accuracy: 0.9375
Training loss: 0.27829, accuracy: 0.921875
Training loss: 0.148887, accuracy: 0.953125
Training loss: 0.218371, accuracy: 0.90625
Training loss: 0.168415, accuracy: 0.953125
Training loss: 0.0681603, accuracy: 0.984375
Training loss: 0.164589, accuracy: 0.9375
Training loss: 0.121871, accuracy: 0.96875
Training loss: 0.152084, accuracy: 0.9375
Training loss: 0.047361, accuracy: 1.0
Training loss: 0.232823, accuracy: 0.9375
Training loss: 0.131743, accuracy: 0.921875
Training loss: 0.313787, accuracy: 0.875
Training loss: 0.164689, accuracy: 0.953125
Training loss: 0.142013, accuracy: 0.921875
Training loss: 0.207355, accuracy: 0.921875
Training loss: 0.196487, accuracy: 0.9375
Training loss: 0.248578, accuracy: 0.921875
Training loss: 0.114737, accuracy: 0.96875
Training loss: 0.202792, accuracy: 0.921875
Training loss: 0.0791928, accuracy: 0.984375
Training

Training loss: 0.067058, accuracy: 0.96875
Training loss: 0.0864547, accuracy: 0.984375
Training loss: 0.191015, accuracy: 0.96875
Training loss: 0.157078, accuracy: 0.953125
Training loss: 0.233333, accuracy: 0.9375
Training loss: 0.195381, accuracy: 0.953125
Training loss: 0.179292, accuracy: 0.953125
Training loss: 0.115575, accuracy: 0.9375
----------------- Step 1500: validation accuracy 0.84 ----------------
Training loss: 0.0432654, accuracy: 1.0
Training loss: 0.0819222, accuracy: 0.984375
Training loss: 0.151645, accuracy: 0.953125
Training loss: 0.0349077, accuracy: 0.984375
Training loss: 0.117458, accuracy: 0.96875
Training loss: 0.209155, accuracy: 0.9375
Training loss: 0.0503842, accuracy: 1.0
Training loss: 0.0956899, accuracy: 0.96875
Training loss: 0.239771, accuracy: 0.9375
Training loss: 0.0726943, accuracy: 0.984375
Training loss: 0.136448, accuracy: 0.96875
Training loss: 0.100797, accuracy: 0.96875
Training loss: 0.169425, accuracy: 0.953125
Training loss: 0.19071

Training loss: 0.148382, accuracy: 0.96875
Training loss: 0.214785, accuracy: 0.9375
Training loss: 0.100876, accuracy: 0.953125
Training loss: 0.0817711, accuracy: 0.984375
Training loss: 0.106876, accuracy: 0.96875
Training loss: 0.194636, accuracy: 0.9375
Training loss: 0.253508, accuracy: 0.921875
Training loss: 0.113568, accuracy: 0.96875
Training loss: 0.069887, accuracy: 0.96875
Training loss: 0.192005, accuracy: 0.953125
Training loss: 0.137106, accuracy: 0.96875
Training loss: 0.0782728, accuracy: 0.984375
Training loss: 0.158458, accuracy: 0.953125
Training loss: 0.148833, accuracy: 0.9375
Training loss: 0.0468441, accuracy: 0.984375
Training loss: 0.0982963, accuracy: 0.96875
Training loss: 0.0623678, accuracy: 0.984375
Training loss: 0.0741168, accuracy: 0.953125
Training loss: 0.136047, accuracy: 0.953125
Training loss: 0.0597897, accuracy: 0.984375
Training loss: 0.126732, accuracy: 0.9375
Training loss: 0.109527, accuracy: 0.96875
Better accuracy found. LSTM model saved


Training loss: 0.0548815, accuracy: 0.96875
Training loss: 0.0396417, accuracy: 0.984375
Training loss: 0.0363721, accuracy: 0.984375
Training loss: 0.100433, accuracy: 0.984375
Training loss: 0.0184883, accuracy: 1.0
Training loss: 0.0810714, accuracy: 0.984375
Training loss: 0.103483, accuracy: 0.953125
Training loss: 0.101414, accuracy: 0.96875
Training loss: 0.197008, accuracy: 0.953125
Training loss: 0.00622717, accuracy: 1.0
Training loss: 0.0465845, accuracy: 0.984375
Training loss: 0.125437, accuracy: 0.96875
Training loss: 0.0203203, accuracy: 1.0
Training loss: 0.0230628, accuracy: 1.0
Training loss: 0.0483305, accuracy: 0.96875
Training loss: 0.10672, accuracy: 0.953125
Training loss: 0.24902, accuracy: 0.90625
Training loss: 0.0360937, accuracy: 0.984375
Training loss: 0.140988, accuracy: 0.96875
Training loss: 0.0110982, accuracy: 1.0
Training loss: 0.0260522, accuracy: 0.984375
Training loss: 0.0954209, accuracy: 0.984375
Training loss: 0.0578074, accuracy: 0.984375
Train

Training loss: 0.0652676, accuracy: 0.96875
Training loss: 0.0365265, accuracy: 0.984375
Training loss: 0.227183, accuracy: 0.953125
Training loss: 0.0236744, accuracy: 1.0
Training loss: 0.16151, accuracy: 0.9375
Training loss: 0.0136344, accuracy: 1.0
Training loss: 0.103506, accuracy: 0.96875
Training loss: 0.0188843, accuracy: 1.0
Training loss: 0.0292239, accuracy: 1.0
Training loss: 0.043277, accuracy: 0.984375
Training loss: 0.104084, accuracy: 0.953125
Training loss: 0.0563433, accuracy: 0.984375
Training loss: 0.0469383, accuracy: 0.984375
Training loss: 0.10326, accuracy: 0.96875
Training loss: 0.0398159, accuracy: 0.984375
Training loss: 0.0543891, accuracy: 0.984375
Training loss: 0.087815, accuracy: 0.984375
Training loss: 0.0169461, accuracy: 1.0
Training loss: 0.016747, accuracy: 1.0
Training loss: 0.0975059, accuracy: 0.96875
Training loss: 0.158907, accuracy: 0.96875
Training loss: 0.0624446, accuracy: 0.96875
Training loss: 0.0134142, accuracy: 1.0
Training loss: 0.09

Training loss: 0.0134934, accuracy: 1.0
Training loss: 0.0992913, accuracy: 0.984375
Training loss: 0.0677993, accuracy: 0.984375
Training loss: 0.0265921, accuracy: 1.0
Training loss: 0.0635932, accuracy: 0.984375
Training loss: 0.100325, accuracy: 0.984375
Training loss: 0.0244081, accuracy: 1.0
Training loss: 0.00603471, accuracy: 1.0
Training loss: 0.00934772, accuracy: 1.0
Training loss: 0.018811, accuracy: 0.984375
Training loss: 0.0113918, accuracy: 1.0
Training loss: 0.0522434, accuracy: 0.96875
Training loss: 0.0397025, accuracy: 0.984375
Training loss: 0.066626, accuracy: 0.984375
Training loss: 0.10177, accuracy: 0.96875
Training loss: 0.01844, accuracy: 1.0
Training loss: 0.105178, accuracy: 0.984375
Training loss: 0.0548624, accuracy: 0.953125
Training loss: 0.147987, accuracy: 0.953125
Training loss: 0.0572593, accuracy: 0.984375
Training loss: 0.0109132, accuracy: 1.0
Training loss: 0.0490329, accuracy: 0.96875
Training loss: 0.111286, accuracy: 0.984375
Training loss: 0

Training loss: 0.203993, accuracy: 0.9375
Training loss: 0.0300753, accuracy: 1.0
Training loss: 0.0287427, accuracy: 1.0
Training loss: 0.0254767, accuracy: 1.0
Training loss: 0.046626, accuracy: 1.0
Training loss: 0.17085, accuracy: 0.953125
Training loss: 0.019648, accuracy: 1.0
Training loss: 0.0565728, accuracy: 0.984375
Training loss: 0.0578145, accuracy: 0.984375
Training loss: 0.0643665, accuracy: 0.984375
Training loss: 0.0250919, accuracy: 1.0
Training loss: 0.19185, accuracy: 0.96875
Training loss: 0.0176504, accuracy: 1.0
Training loss: 0.0415388, accuracy: 0.984375
Training loss: 0.0719822, accuracy: 0.984375
Training loss: 0.033604, accuracy: 0.984375
Training loss: 0.138282, accuracy: 0.96875
Training loss: 0.0198183, accuracy: 1.0
Training loss: 0.0281711, accuracy: 1.0
Training loss: 0.082809, accuracy: 0.96875
Training loss: 0.134533, accuracy: 0.984375
Training loss: 0.0733915, accuracy: 0.984375
Training loss: 0.0767985, accuracy: 0.984375
Training loss: 0.065818, a

Training loss: 0.0325629, accuracy: 0.984375
Training loss: 0.00703875, accuracy: 1.0
Training loss: 0.00468951, accuracy: 1.0
Training loss: 0.0114325, accuracy: 1.0
Training loss: 0.0307266, accuracy: 0.984375
Training loss: 0.123169, accuracy: 0.953125
Training loss: 0.00942139, accuracy: 1.0
Training loss: 0.00493224, accuracy: 1.0
Training loss: 0.0754893, accuracy: 0.984375
Training loss: 0.0142843, accuracy: 1.0
Training loss: 0.120907, accuracy: 0.96875
Training loss: 0.00885126, accuracy: 1.0
Training loss: 0.0646895, accuracy: 0.984375
Training loss: 0.00927762, accuracy: 1.0
Training loss: 0.103588, accuracy: 0.984375
Training loss: 0.00738846, accuracy: 1.0
Training loss: 0.00479009, accuracy: 1.0
Training loss: 0.124303, accuracy: 0.96875
Training loss: 0.112396, accuracy: 0.984375
Training loss: 0.0108885, accuracy: 1.0
Training loss: 0.0193091, accuracy: 0.984375
Training loss: 0.127467, accuracy: 0.96875
Training loss: 0.175572, accuracy: 0.96875
Training loss: 0.011509

Training loss: 0.144562, accuracy: 0.96875
Training loss: 0.00232765, accuracy: 1.0
Training loss: 0.0105619, accuracy: 1.0
Training loss: 0.00494102, accuracy: 1.0
Training loss: 0.0612438, accuracy: 0.96875
Training loss: 0.205858, accuracy: 0.953125
Training loss: 0.0753361, accuracy: 0.984375
Training loss: 0.0493096, accuracy: 0.984375
Training loss: 0.089149, accuracy: 0.984375
Training loss: 0.0439961, accuracy: 0.984375
Training loss: 0.191104, accuracy: 0.9375
Training loss: 0.0527923, accuracy: 0.984375
Training loss: 0.159295, accuracy: 0.953125
Training loss: 0.0654832, accuracy: 0.984375
Training loss: 0.0359975, accuracy: 0.984375
Training loss: 0.0630717, accuracy: 0.984375
Training loss: 0.0107649, accuracy: 1.0
Training loss: 0.0902274, accuracy: 0.96875
Training loss: 0.0114415, accuracy: 1.0
Training loss: 0.0323628, accuracy: 0.984375
Training loss: 0.0228841, accuracy: 1.0
Training loss: 0.12039, accuracy: 0.96875
Training loss: 0.0697678, accuracy: 0.984375
Traini

Training loss: 0.0415136, accuracy: 0.984375
Training loss: 0.124718, accuracy: 0.9375
Training loss: 0.00771718, accuracy: 1.0
Training loss: 0.105167, accuracy: 0.984375
Training loss: 0.038545, accuracy: 0.984375
----------------- Step 3000: validation accuracy 0.828 ----------------
Training loss: 0.0361813, accuracy: 0.984375
Training loss: 0.0336925, accuracy: 0.984375
Training loss: 0.0757634, accuracy: 0.984375
Training loss: 0.0643787, accuracy: 0.984375
Training loss: 0.103072, accuracy: 0.984375
Training loss: 0.0101914, accuracy: 1.0
Training loss: 0.163814, accuracy: 0.953125
Training loss: 0.0445277, accuracy: 0.984375
Training loss: 0.122119, accuracy: 0.96875
Training loss: 0.174295, accuracy: 0.953125
Training loss: 0.0133802, accuracy: 1.0
Training loss: 0.15715, accuracy: 0.984375
Training loss: 0.157614, accuracy: 0.96875
Training loss: 0.0994804, accuracy: 0.984375
Training loss: 0.0145148, accuracy: 1.0
Training loss: 0.0122136, accuracy: 1.0
Training loss: 0.0269

Training loss: 0.0135703, accuracy: 1.0
Training loss: 0.0345062, accuracy: 0.984375
Training loss: 0.0105709, accuracy: 1.0
Training loss: 0.0566323, accuracy: 0.984375
Training loss: 0.0222071, accuracy: 0.984375
Training loss: 0.0102773, accuracy: 1.0
Training loss: 0.00662083, accuracy: 1.0
Training loss: 0.0470131, accuracy: 0.984375
Training loss: 0.00981373, accuracy: 1.0
Training loss: 0.00521857, accuracy: 1.0
Training loss: 0.00503161, accuracy: 1.0
Training loss: 0.00814203, accuracy: 1.0
Training loss: 0.00332261, accuracy: 1.0
Training loss: 0.00631409, accuracy: 1.0
Training loss: 0.13343, accuracy: 0.96875
----------------- Step 3200: validation accuracy 0.79232 ----------------
Training loss: 0.0434676, accuracy: 0.984375
Training loss: 0.0142983, accuracy: 1.0
Training loss: 0.003297, accuracy: 1.0
Training loss: 0.0139218, accuracy: 1.0
Training loss: 0.00448707, accuracy: 1.0
Training loss: 0.0807263, accuracy: 0.984375
Training loss: 0.0672435, accuracy: 0.984375
Tr

Training loss: 0.00490888, accuracy: 1.0
Training loss: 0.0829615, accuracy: 0.984375
Training loss: 0.015369, accuracy: 1.0
Training loss: 0.0134537, accuracy: 1.0
Training loss: 0.0148629, accuracy: 0.984375
Training loss: 0.0793731, accuracy: 0.984375
Training loss: 0.00527884, accuracy: 1.0
Training loss: 0.0831615, accuracy: 0.984375
Training loss: 0.010834, accuracy: 1.0
Training loss: 0.0126926, accuracy: 1.0
Training loss: 0.082126, accuracy: 0.96875
Training loss: 0.0407245, accuracy: 0.984375
Training loss: 0.0376254, accuracy: 0.984375
Training loss: 0.00557747, accuracy: 1.0
Training loss: 0.0171075, accuracy: 1.0
Training loss: 0.0180847, accuracy: 1.0
Training loss: 0.0149796, accuracy: 1.0
Training loss: 0.00627545, accuracy: 1.0
Training loss: 0.00821392, accuracy: 1.0
Training loss: 0.0437779, accuracy: 0.984375
Training loss: 0.00864397, accuracy: 1.0
Training loss: 0.0591329, accuracy: 0.96875
Training loss: 0.0132963, accuracy: 1.0
Training loss: 0.0369567, accuracy

Training loss: 0.00958412, accuracy: 1.0
Training loss: 0.0708108, accuracy: 0.984375
Training loss: 0.115347, accuracy: 0.984375
Training loss: 0.00487304, accuracy: 1.0
Training loss: 0.00348075, accuracy: 1.0
Training loss: 0.00498819, accuracy: 1.0
Training loss: 0.138793, accuracy: 0.953125
Training loss: 0.0104019, accuracy: 1.0
Training loss: 0.143838, accuracy: 0.96875
Training loss: 0.00439816, accuracy: 1.0
Training loss: 0.14089, accuracy: 0.96875
Training loss: 0.112062, accuracy: 0.984375
Training loss: 0.00606781, accuracy: 1.0
Training loss: 0.103009, accuracy: 0.96875
Training loss: 0.0624784, accuracy: 0.984375
Training loss: 0.00378846, accuracy: 1.0
Training loss: 0.00565438, accuracy: 1.0
Training loss: 0.00979786, accuracy: 1.0
Training loss: 0.00523635, accuracy: 1.0
Training loss: 0.130282, accuracy: 0.96875
Training loss: 0.00403378, accuracy: 1.0
Training loss: 0.00538069, accuracy: 1.0
Training loss: 0.00553317, accuracy: 1.0
Training loss: 0.0137299, accuracy

Training loss: 0.00863955, accuracy: 1.0
Training loss: 0.0836421, accuracy: 0.984375
Training loss: 0.0220965, accuracy: 0.984375
Training loss: 0.0170911, accuracy: 1.0
Training loss: 0.00523265, accuracy: 1.0
Training loss: 0.0108271, accuracy: 1.0
Training loss: 0.00915665, accuracy: 1.0
Training loss: 0.0739001, accuracy: 0.984375
Training loss: 0.00682142, accuracy: 1.0
Training loss: 0.0136427, accuracy: 1.0
Training loss: 0.133258, accuracy: 0.984375
Training loss: 0.00996572, accuracy: 1.0
Training loss: 0.0120265, accuracy: 1.0
Training loss: 0.0126267, accuracy: 1.0
Training loss: 0.00954253, accuracy: 1.0
Training loss: 0.0109479, accuracy: 1.0
Training loss: 0.094061, accuracy: 0.984375
Training loss: 0.0208464, accuracy: 0.984375
Training loss: 0.00392678, accuracy: 1.0
Training loss: 0.00281034, accuracy: 1.0
Training loss: 0.00373045, accuracy: 1.0
Training loss: 0.00687993, accuracy: 1.0
Training loss: 0.00847485, accuracy: 1.0
Training loss: 0.00497742, accuracy: 1.0


Training loss: 0.0094884, accuracy: 1.0
Training loss: 0.0542534, accuracy: 0.984375
Training loss: 0.0119227, accuracy: 1.0
Training loss: 0.00328983, accuracy: 1.0
Training loss: 0.0293858, accuracy: 0.984375
Training loss: 0.00795321, accuracy: 1.0
Training loss: 0.0078708, accuracy: 1.0
Training loss: 0.00401223, accuracy: 1.0
Training loss: 0.0128651, accuracy: 1.0
Training loss: 0.0909487, accuracy: 0.96875
Training loss: 0.0112966, accuracy: 1.0
Training loss: 0.00977072, accuracy: 1.0
Training loss: 0.0510739, accuracy: 0.984375
Training loss: 0.00400096, accuracy: 1.0
Training loss: 0.00361933, accuracy: 1.0
Training loss: 0.00162759, accuracy: 1.0
Training loss: 0.0669596, accuracy: 0.984375
Training loss: 0.00224342, accuracy: 1.0
Training loss: 0.129709, accuracy: 0.984375
Training loss: 0.0923357, accuracy: 0.984375
Training loss: 0.00425163, accuracy: 1.0
Training loss: 0.0235449, accuracy: 0.984375
Training loss: 0.00376143, accuracy: 1.0
Training loss: 0.0653592, accura

Training loss: 0.0528412, accuracy: 0.96875
Training loss: 0.00625049, accuracy: 1.0
Training loss: 0.00777792, accuracy: 1.0
Training loss: 0.00807116, accuracy: 1.0
Training loss: 0.00765875, accuracy: 1.0
Training loss: 0.119954, accuracy: 0.953125
Training loss: 0.00426617, accuracy: 1.0
Training loss: 0.0148935, accuracy: 1.0
Training loss: 0.00589013, accuracy: 1.0
Training loss: 0.147879, accuracy: 0.96875
Training loss: 0.00164325, accuracy: 1.0
Training loss: 0.00429739, accuracy: 1.0
Training loss: 0.0619085, accuracy: 0.96875
Training loss: 0.0163886, accuracy: 1.0
Training loss: 0.0028445, accuracy: 1.0
Training loss: 0.0062544, accuracy: 1.0
Training loss: 0.00817794, accuracy: 1.0
Training loss: 0.107122, accuracy: 0.984375
Training loss: 0.0101572, accuracy: 1.0
Training loss: 0.0196584, accuracy: 0.984375
Training loss: 0.00749305, accuracy: 1.0
Training loss: 0.129191, accuracy: 0.984375
Training loss: 0.0037678, accuracy: 1.0
Training loss: 0.00263501, accuracy: 1.0
T

Training loss: 0.00519823, accuracy: 1.0
Training loss: 0.00712185, accuracy: 1.0
Training loss: 0.00438812, accuracy: 1.0
Training loss: 0.00328795, accuracy: 1.0
Training loss: 0.00406151, accuracy: 1.0
Training loss: 0.0045388, accuracy: 1.0
Training loss: 0.00989388, accuracy: 1.0
Training loss: 0.0157951, accuracy: 0.984375
Training loss: 0.00223423, accuracy: 1.0
Training loss: 0.0116598, accuracy: 1.0
Training loss: 0.00375965, accuracy: 1.0
Training loss: 0.00289106, accuracy: 1.0
Training loss: 0.0137072, accuracy: 0.984375
Training loss: 0.0113794, accuracy: 1.0
Training loss: 0.00681696, accuracy: 1.0
Training loss: 0.0342251, accuracy: 0.984375
Training loss: 0.00306145, accuracy: 1.0
Training loss: 0.00412127, accuracy: 1.0
Training loss: 0.0823173, accuracy: 0.984375
Training loss: 0.00249272, accuracy: 1.0
Training loss: 0.00253575, accuracy: 1.0
Training loss: 0.117055, accuracy: 0.984375
Training loss: 0.00175266, accuracy: 1.0
Training loss: 0.00456534, accuracy: 1.0


Training loss: 0.0610654, accuracy: 0.984375
Training loss: 0.00676377, accuracy: 1.0
Training loss: 0.00549809, accuracy: 1.0
Training loss: 0.00302354, accuracy: 1.0
Training loss: 0.00147925, accuracy: 1.0
Training loss: 0.00345621, accuracy: 1.0
Training loss: 0.00278938, accuracy: 1.0
Training loss: 0.0603484, accuracy: 0.984375
Training loss: 0.00792425, accuracy: 1.0
Training loss: 0.00320166, accuracy: 1.0
Training loss: 0.00318812, accuracy: 1.0
Training loss: 0.002765, accuracy: 1.0
Training loss: 0.00291009, accuracy: 1.0
Training loss: 0.00551585, accuracy: 1.0
Training loss: 0.00218708, accuracy: 1.0
Training loss: 0.0184863, accuracy: 0.984375
Training loss: 0.00194245, accuracy: 1.0
Training loss: 0.00903565, accuracy: 1.0
Training loss: 0.00181011, accuracy: 1.0
Training loss: 0.0708493, accuracy: 0.96875
Training loss: 0.00678607, accuracy: 1.0
Training loss: 0.0159245, accuracy: 0.984375
Training loss: 0.0659013, accuracy: 0.96875
Training loss: 0.0952354, accuracy: 0

Training loss: 0.00513043, accuracy: 1.0
Training loss: 0.106284, accuracy: 0.984375
Training loss: 0.0129687, accuracy: 1.0
Training loss: 0.0066368, accuracy: 1.0
Training loss: 0.00759397, accuracy: 1.0
Training loss: 0.0248049, accuracy: 0.984375
Training loss: 0.0106188, accuracy: 1.0
Training loss: 0.00723049, accuracy: 1.0
Training loss: 0.0203069, accuracy: 0.984375
Training loss: 0.00357334, accuracy: 1.0
Training loss: 0.0578045, accuracy: 0.984375
Training loss: 0.0390613, accuracy: 0.984375
Training loss: 0.0108876, accuracy: 1.0
Training loss: 0.00391955, accuracy: 1.0
Training loss: 0.00727179, accuracy: 1.0
Training loss: 0.00294991, accuracy: 1.0
Training loss: 0.0671941, accuracy: 0.984375
Training loss: 0.00662755, accuracy: 1.0
Training loss: 0.00404395, accuracy: 1.0
Training loss: 0.00276867, accuracy: 1.0
Training loss: 0.126809, accuracy: 0.984375
Training loss: 0.00325459, accuracy: 1.0
Training loss: 0.00601155, accuracy: 1.0
Training loss: 0.0343877, accuracy:

Training loss: 0.0281824, accuracy: 0.984375
Training loss: 0.0160642, accuracy: 0.984375
Training loss: 0.00319698, accuracy: 1.0
Training loss: 0.0646329, accuracy: 0.984375
Training loss: 0.0349235, accuracy: 0.96875
Training loss: 0.00652195, accuracy: 1.0
Training loss: 0.00220341, accuracy: 1.0
Training loss: 0.00366302, accuracy: 1.0
Training loss: 0.116826, accuracy: 0.984375
Training loss: 0.00308413, accuracy: 1.0
Training loss: 0.00308918, accuracy: 1.0
Training loss: 0.0183787, accuracy: 0.984375
Training loss: 0.0154482, accuracy: 1.0
Training loss: 0.021238, accuracy: 0.984375
Training loss: 0.0509633, accuracy: 0.984375
Training loss: 0.0213522, accuracy: 0.984375
Training loss: 0.00565588, accuracy: 1.0
Training loss: 0.00319117, accuracy: 1.0
Training loss: 0.0027498, accuracy: 1.0
Training loss: 0.106513, accuracy: 0.96875
Training loss: 0.00309907, accuracy: 1.0
Training loss: 0.00380978, accuracy: 1.0
Training loss: 0.00763373, accuracy: 1.0
Training loss: 0.0078687

# Let's do a test 

In [76]:
raw_text1 = "This is such a horrible movie"
raw_text2 = "OMG, this is such an amazing movie. I love it!"
raw_text3 = "It is okay. Not too bad"

In [77]:
lstm_model.predict(raw_text1)

[[ 0.97637618  0.02362388]]


In [78]:
lstm_model.predict(raw_text2)

[[  7.06913113e-07   9.99999285e-01]]


In [79]:
lstm_model.predict(raw_text3)

[[  9.99948263e-01   5.16991240e-05]]


In [80]:
sample_dataset, label = lstm_model.data_helper.load_raw_data()
sample_dataset = sample_dataset.head()

In [81]:
sample_dataset

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [82]:
import numpy as np

In [83]:
sample0 = sample_dataset.review[0]
sample1 = sample_dataset.review[1]
sample2 = sample_dataset.review[2]
sample3 = sample_dataset.review[3]

# labels = np.array(sample_dataset.sentiment)
# labels_onehot = np.zeros((labels.shape[0], 2))
# labels_onehot[np.arange(len(labels_onehot)), labels] = 1

In [84]:
lstm_model.predict(sample0)

[[  6.56751173e-12   1.00000000e+00]]


In [85]:
lstm_model.predict(sample1)

[[  5.14126025e-12   1.00000000e+00]]


In [87]:
lstm_model.predict(sample2)

[[  1.00000000e+00   2.98706226e-10]]


In [88]:
lstm_model.predict(sample3)

[[  9.99745905e-01   2.54134357e-04]]
