In [1]:
import os
import sys
import importlib

In [2]:
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
import src.popcorn as popcorn

In [4]:
popcorn_helper = popcorn.PopcornHelper(root_directory=module_path)

In [5]:
train_raw, test_raw = popcorn_helper.load_raw_data()

In [7]:
train_raw.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [8]:
test_raw.head()

id                                             review
0  12311_10  Naturally in a film who's main themes are of m...
1    8348_2  This movie is a disaster within a disaster fil...
2    5828_4  All in all, this is a movie for kids. We saw i...
3    7186_2  Afraid of the Dark left me with the impression...
4   12128_7  A very accurate depiction of small time mob li...

In [9]:
sentence_list_clean = popcorn_helper.clean_dtset(train_raw.head(), sentence_col_name="review")

In [10]:
corpora_dict = popcorn_helper.build_save_dictionary(sentence_list_clean)

In [11]:
sentence_list_clean2 = popcorn_helper.clean_dtset(test_raw.head(), sentence_col_name="review")

In [12]:
import numpy as np

In [10]:
importlib.reload(popcorn)
popcorn_helper = popcorn.PopcornHelper(root_directory=module_path)

In [14]:
np.array(popcorn_helper.doc_2_ids(sentence_list_clean2, corpora_dict))

array([ list([294, 51, -1, 621, -1, -1, -1, 65, -1, -1, 189, -1, -1, -1, -1, 100, 274, -1, -1, 51, -1, 165, -1, -1, -1, 22, 261, -1, 592, -1, 294, -1, 575, -1, -1, -1, -1, -1, -1, 535, -1, -1, -1, 638, -1, -1, 294, -1, -1, 344, -1, 51, -1, 82, 616, -1, -1, 525, 335, -1, -1, 83, -1, -1, -1, -1, 140, -1, -1, -1, -1, -1]),
       list([93, 396, -1, 396, 51, 261, 175, -1, 328, -1, -1, 6, 462, -1, 74, 121, -1, -1, -1, -1, -1, -1, 385, -1, -1, -1, -1, -1, -1, 409, -1, 74, 1, -1, 100, 327, 135, -1, 0, -1, -1, 15, 15, 530, -1, -1, -1, 133, -1, 83, 51, -1, -1, 0, 266, -1, 214, 415, -1, -1, 452, 601, 369, 133, -1, -1, -1, 153, 93, 126, -1, 180, 6, 77, 626, -1, -1, 72, 160, 146, 180, 6, -1, 623, -1, -1]),
       list([93, 70, -1, -1, -1, -1, 100, -1, 70, 254, 175, -1, -1, 274, 175, 48, -1, 158, 131, -1, -1, -1, 8, -1, -1, -1, 22, 51, 131, 333, -1, -1, 121, -1, 83, 93, 344, -1, -1, -1, -1, -1, 355, 173, -1, -1, -1, -1, -1, 22, 495, 266, 114, -1, -1, 94, 274, -1, -1, 103, 524, -1, 15, 15, 344, 12, 

In [15]:
import pandas as pd
import numpy as np 

In [11]:
X_train, X_test, y_train = popcorn_helper.get_train_test()

Cleaned data exists, load directly from pickle file


In [12]:
X_train = popcorn_helper.pad_sequence(input_data=X_train, max_len=200)

In [13]:
X_train.shape

(25000, 200)

In [14]:
X_train[0: 3]

array([[128,  58,  91,  90, 126,  79,  94, 146,  99,  36, 146, 151, 146,
         92,  85, 145,  55,  21,  66,  61, 136, 114,  28,  41,  85,  83,
         88, 148,  60,  65,  92, 103,  11, 103,  49,  51, 116,  58, 121,
         23, 101, 115, 131,  86,  90,  50, 137, 111,   2,  98,  86,  38,
          7,  15,  15, 144,  64,  29,  87,  68, 142, 117,  77,  90,   4,
         58,  62,  53,  13,  84,  18,  90,  40,  26,  83,  93,  90,  48,
        153, 120,  82,  48, 139, 114,  97,  15,  15,   0,  49,  51,  12,
         52, 126,  89,  45, 124,  30, 122,  69, 107,  27, 112, 110,  38,
         80, 145,  90,  32,   7,  10,  90, 102, 108,  96,  69, 107,  22,
        113, 145, 105,  72, 132,  38,  43,  39,  85,  62,  90,  15,  15,
         81,  28, 134,  77,  90, 141,  20, 118, 149, 125,  33, 122,   2,
         35,  95, 104, 119,  19,  51,  71,   7, 122, 143,  35,  62, 152,
        100,  70,  74,   1, 149,  17, 106,  25,  31,  15,  15,  14,  78,
         93, 105,  77,  90, 100,  75,   3, 135, 105

In [26]:
np.pad(test_seq, [2, 3], 'constant')

array([0, 0, list([1, 2, 3]), list([2]), list([1, 2, 3, 4]), 0, 0, 0], dtype=object)

In [44]:
a = [[1, 2, 3, 4], [2, 3, 4], [1], [2, 3 , 6]]

In [45]:
popcorn_helper.pad_sequence(a, 6)

array([[ 1.,  2.,  3.,  4.,  0.,  0.],
       [ 2.,  3.,  4.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  3.,  6.,  0.,  0.,  0.]])

In [16]:
sample_sentence = [['a', 'b', 'c'], ['d', 'e', 'f']]

In [32]:
from gensim import corpora

In [33]:
cd = corpora.Dictionary(sample_sentence)

In [34]:
cd

In [35]:
cd.token2id

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5}

In [36]:
cd.patch_with_special_tokens({
    '<PADDNING>': 0,
    '<UNKNOWN>': 1
})

In [37]:
cd.token2id

{'<PADDNING>': 0,
 '<UNKNOWN>': 1,
 'a': 7,
 'b': 6,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5}

In [38]:
cd.doc2idx(['a', 'b', 'n'])

[7, 6, -1]